# Start with the golang v1.13 image
FROM  golang:1.16-stretch

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Install all go_modules
RUN go mod tidy
RUN go mod download

# Specify the command from running tests
CMD go clean -testcache && go test -v -tags sqlite_json ./test/...